name: piczilla
description: "PicZilla - Browse, Search, Collect"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.3.0
  http: ^1.2.2
  intl: ^0.19.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  golden_toolkit: ^0.15.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

